### ISSUE TITLE
Missing documentation for use lexicon_path in mapping

### ISSUE THREAD

**Issue by havran** [vhyza/elasticsearch-analysis-lemmagen#10]
This feature is undocumented in  readme.

```
        ...
        "filter": {
          "lemmagen_filter_my": {
            "type": "lemmagen",
            "lexicon_path": "directory_in_es_config/my_lexicon.lem"
          }
        },
        ...
```

**Comment by vhyza** [comment]
Thank you for the information. I know about it. All lexicons are part of the plugin right now. I'm preparing lexicons with less restrictive licence which will be part of another repository, when it is finished, it'll be documented...:)
