### ISSUE TITLE
Support for 7.3.0

### ISSUE THREAD

**Issue by matejsoroka** [vhyza/elasticsearch-analysis-lemmagen#15]
Hey, is support for v7.3.0 planned? It would be amazing :)

**Comment by vhyza** [comment]
Hi, yes it is planned. If there are no breaking changes I expect to release all missing versions (6.8.2, 7.2.1, 7.3.0) later today...

**Comment by matejsoroka** [comment]
Amazing, thanks for quick response :)

**Comment by vhyza** [comment]
Here you go https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.3.0 :)

**Comment by pySilver** [comment]
hello @vhyza! Thanks for you good work. Do you plan to add 7.9.x support anytime soon?

**Comment by vhyza** [comment]
Hi @pySilver, yes I expect to release the missing versions (6.8.12, 7.9.0, 7.9.1 and 7.9.2) later today if everything goes as planned :-)

**Comment by vhyza** [comment]
@pySilver, here you go :-)

https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v6.8.12
https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.9.0
https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.9.1
https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.9.2

**Comment by pySilver** [comment]
Thank you!
