### ISSUE TITLE
Error "Not in GZip format" while trying to create the index

### ISSUE THREAD

**Issue by schmarine** [vhyza/elasticsearch-analysis-lemmagen#16]
Hello,

I am trying to use your plugin in my Docker application that uses ElasticSearch.
Here are the lines I wrote in my `docker-compose` to install the plugin for English:

    /tmp/es-install-plugin.sh https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/download/v7.5.1/elasticsearch-analysis-lemmagen-7.5.1-plugin.zip &&
    mkdir -p /usr/share/elasticsearch/config/lemmagen &&
    curl -o /usr/share/elasticsearch/config/lemmagen/en.lem https://github.com/vhyza/lemmagen-lexicons/raw/master/free/lexicons/en.lem

But when I am trying to create the index it brings me the following error :

<img width="1430" alt="Capture d’écran 2020-03-02 à 19 01 42" src="https://user-images.githubusercontent.com/61305456/75704080-f86f4100-5cb8-11ea-9d9d-9278349a8184.png">

Any idea why do I get this?
Thank you!

**Comment by vhyza** [comment]
Hi @schmarine ,

I think, that the lexicon is not correctly downloaded. When I tried your command:

```
curl -o /usr/share/elasticsearch/config/lemmagen/en.lem https://github.com/vhyza/lemmagen-lexicons/raw/master/free/lexicons/en.lem
```

it saved just the HTML with redirection. Try to add `-L` to curl options to follow redirects.

```
curl -L -o /usr/share/elasticsearch/config/lemmagen/en.lem https://github.com/vhyza/lemmagen-lexicons/raw/master/free/lexicons/en.lem
```

**Comment by schmarine** [comment]
It worked fine, thanks a lot !

**Comment by vhyza** [comment]
Great, you are welcome.
