### ISSUE TITLE
Add 7.10 support

### ISSUE THREAD

**Issue by tonykoval** [vhyza/elasticsearch-analysis-lemmagen#19]
Add support to Elasticsearch 7.10 support. Check: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.10.0.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.10.html

Thank you.

**Comment by vhyza** [comment]
@tonykoval here you go :-)

https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.10.0
