### ISSUE TITLE
Doesn't work on 2.1.1

### ISSUE THREAD

**Issue by radeno** [vhyza/elasticsearch-analysis-lemmagen#2]
Hi,

i really like this plugin to Elasticsearch.
But i dont know what Elastic changed to version 2.1.1 but when i want install Lemmagen 2.1 i get:
```ERROR: Plugin [elasticsearch-analysis-lemmagen] is incompatible with Elasticsearch [2.1.1]. Was designed for version [2.1.0]```

Reverting back to Elasticsearch 2.1.0.

**Comment by vhyza** [comment]
Hello,

thank you for the information. According to https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html there is need to release a new version of the plugin for each new elasticsearch release.

I updated and released new version of plugin. You can test it by `./bin/plugin install https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/download/v2.1.1/elasticsearch-analysis-lemmagen-2.1.1-plugin.zip`
