### ISSUE TITLE
Add 7.10.2 support

### ISSUE THREAD

**Issue by Skivholme** [vhyza/elasticsearch-analysis-lemmagen#20]
Do you plan on making support for 7.10.2 ?

https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.10.2.html

Thank you.

**Comment by vhyza** [comment]
@Skivholme here you go :-)

https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.10.2
