### ISSUE TITLE
Add 7.11 support

### ISSUE THREAD

**Issue by tonykoval** [vhyza/elasticsearch-analysis-lemmagen#21]
Add support to Elasticsearch 7.11.1 support. Thank you.

**Comment by vhyza** [comment]
Hi @tonykoval, here you go :-)

https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.11.1

**Comment by vhyza** [comment]
@tonykoval FYI: I also released https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.11.2 so if you are upgrading maybe you can skip the 7.11.1 version ;-)
