### ISSUE TITLE
Preserve original form of input/word

### ISSUE THREAD

**Issue by radeno** [vhyza/elasticsearch-analysis-lemmagen#22]
Hi,

thanks for this awesome module and your work.

Like many others (mostly built-in) filters in elastic search allows the option to preserve original string even is somehow processed. Eg ASCII-Folding https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html#analysis-asciifolding-tokenfilter-configure-parms allows us to preserve original.
This is a very nice feature when we want to work with multiple forms of user input.

Many words after lemmatizing can have a different basis of words or meaning because input from the user is not always perfect. So the final result can be a little bit different and leads to different results than we expect.

What is your opinion on this option?

**Comment by vhyza** [comment]
Hi @radeno,

thank you for your kind words.

Please correct me if I'm wrong, but isn't this doable using https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis-keyword-repeat-tokenfilter.html? So for example

```json
PUT /lemmagen-test
{
  "settings": {
    "index": {
      "analysis": {
        "filter": {
          "lemmagen_filter_en": {
            "type": "lemmagen",
            "lexicon": "en"
          }
        },
        "analyzer": {
          "lemmagen_en": {
            "type": "custom",
            "tokenizer": "uax_url_email",
            "filter": [
              "keyword_repeat",
              "lemmagen_filter_en"
            ]
          }
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "text": {
        "type": "text",
        "analyzer": "lemmagen_en"
      }
    }
  }
}
```

And when I do _analyze

```json
GET /lemmagen-test/_analyze
{
  "text": "I am",
  "analyzer": "lemmagen_en"
}
```

I get

```json
{
  "tokens": [
    {
      "token": "I",
      "start_offset": 0,
      "end_offset": 1,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "I",
      "start_offset": 0,
      "end_offset": 1,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "am",
      "start_offset": 2,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 1
    },
    {
      "token": "be",
      "start_offset": 2,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 1
    }
  ]
}
```

If you want to remove the duplicated tokens, you can use https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis-remove-duplicates-tokenfilter.html

```json
PUT /lemmagen-test
{
  "settings": {
    "index": {
      "analysis": {
        "filter": {
          "lemmagen_filter_en": {
            "type": "lemmagen",
            "lexicon": "en"
          }
        },
        "analyzer": {
          "lemmagen_en": {
            "type": "custom",
            "tokenizer": "uax_url_email",
            "filter": [
              "keyword_repeat",
              "lemmagen_filter_en",
              "remove_duplicates"
            ]
          }
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "text": {
        "type": "text",
        "analyzer": "lemmagen_en"
      }
    }
  }
}
```

which returns following for the same _analyze query

```json
{
  "tokens": [
    {
      "token": "I",
      "start_offset": 0,
      "end_offset": 1,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "am",
      "start_offset": 2,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 1
    },
    {
      "token": "be",
      "start_offset": 2,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 1
    }
  ]
}
```

**Comment by radeno** [comment]
Didn't know about `repeat_keyword` filter. Thank you!

And, you are right. With `keyword_repeat` and `remove_duplicates` results are as expected.

I am a little bit puzzled between `keyword_repeat` filter and `preserve_original` option.
Looks like `keyword_repeat` will add `keyword` property, which prevents only stemmers from process, because for example ASCII-Folding doesn't respect it :) 

Anyway, thank you again for your help!

**Comment by vhyza** [comment]
You are welcome.

That is my understanding too, that `keyword_repeat` is emitting each token twice. Once marked as keyword and once as non-keyword.

This plugin understands it thanks to https://github.com/vhyza/elasticsearch-analysis-lemmagen/pull/9
