### ISSUE TITLE
Elasticsearch 7.16.1

### ISSUE THREAD

**Issue by KazaBen** [vhyza/elasticsearch-analysis-lemmagen#25]
Hi, 

We are planning to update Elasticsearch to `7.16.1`, could you update the plugin for `7.16.1` version?

Thank you so much! :) 

@vhyza

**Comment by KazaBen** [comment]
Created PR: https://github.com/vhyza/elasticsearch-analysis-lemmagen/pull/26

**Comment by vhyza** [comment]
Hi @KazaBen,

thank you for the PR. I'll try to release missing plugin versions during today...

**Comment by vhyza** [comment]
@KazaBen here you go :-)

https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.16.1
