### ISSUE TITLE
Add 6.8.23 support

### ISSUE THREAD

**Issue by samigarali** [vhyza/elasticsearch-analysis-lemmagen#28]
Hello,

i want to upgrade to es 6.8.23 and not 6.8.22 so can you add support for this version please ? 

thank you

**Comment by vhyza** [comment]
Hi @samigarali,

I'm attaching the compiled plugin from https://github.com/vhyza/elasticsearch-analysis-lemmagen/tree/elasticsearch-6 branch. I'll do proper release at the weekend (hopefully 🙂).

[elasticsearch-analysis-lemmagen-6.8.23-plugin.zip](https://github.com/vhyza/elasticsearch-analysis-lemmagen/files/8466320/elasticsearch-analysis-lemmagen-6.8.23-plugin.zip)

**Comment by samigarali** [comment]
thank you for your reactivity. 

I will use the zip for testing until the weekend for the final release

**Comment by samigarali** [comment]
friendly reminder for the release

**Comment by vhyza** [comment]
@samigarali, thanks for the reminder, but in the end I wasn't able to do it. Hopefully this weekend... Anyway in your case should not matter as the actual plugin zip will be the same as the one in https://github.com/vhyza/elasticsearch-analysis-lemmagen/issues/28#issuecomment-1095317341

**Comment by samigarali** [comment]
Yes true, but i have an automated download from github when i create a release. Otherwise, I have to change a little bit the code and inject manually the zip. Thank you

**Comment by vhyza** [comment]
@samigarali Oh, I see. Here you go https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v6.8.23
