### ISSUE TITLE
Elasticsearch version 7.17.4

### ISSUE THREAD

**Issue by med502** [vhyza/elasticsearch-analysis-lemmagen#29]
Plugin does not have version compatible with elastic 7.17.4.
Would you be able to create it?

**Comment by vhyza** [comment]
Hi @med502, yes I'm planning to release missing versions, but in the end of the next week as I'm currently on holiday...

**Comment by med502** [comment]
> Hi @med502, yes I'm planning to release missing versions, but in the end of the next week as I'm currently on holiday...

That would be great, thank you!
Enjoy your time off.

**Comment by vhyza** [comment]
Hi @med502,

sorry for the delay..

I just released missing versions for v7 branch:

[v7.17.4](https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.17.4)
[v7.17.5](https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.17.5)
