### ISSUE TITLE
Could it be used with porter_stem?

### ISSUE THREAD

**Issue by ArtemBernatskyy** [vhyza/elasticsearch-analysis-lemmagen#32]
Hi, thx for the awesome work, small question.

Could `lemmagen` filter be used with `porter_stem` filter (for English language)? And if yes what pros and cons? Thx!

Example of querying:
```
GET /lemmagen-test/_analyze
{
  "tokenizer": "standard",
  "filter": [
    "lowercase",
    "lemmagen_filter_en",
    "porter_stem"
  ],
  "text": "some text to test analyser"
}
```

**Comment by vhyza** [comment]
Hi @ArtemBernatskyy,

thank you for your kind words.

About the lemmagen + porter_stem filter, I guess it is technically possible, but I'm unsure about some benefits. Both filters tries to convert word in some form (with prefixes and suffixes) to some "more general" form to be able to search for words in different forms (for example singular vs plural).

AFAIK porter_stem filter and lemmagen_filter_en are using different methods to achieve this.

porter_stem use [stemming](https://en.wikipedia.org/wiki/Stemming) which removes suffixes etc from the word so the result can be part of the word. For example for `"apples"` it would be `"appl"`

```
GET /lemmagen-test/_analyze
{
  "tokenizer": "standard",
  "filter": [
    "lowercase",
    "porter_stem"
  ],
  "text": "apples"
}
```

and for `"apple"` it would be `"appl"` too

```
GET /lemmagen-test/_analyze
{
  "tokenizer": "standard",
  "filter": [
    "lowercase",
    "porter_stem"
  ],
  "text": "apple"
}
```

So as the query is processed with the same field analyzers in query time we will get documents for `"apples"` query even if document contains `"apple"` (as for both the stem is `"appl"`)

On the other hand lemmagen is using the dictionary to guess the canonical form of the word. So for `"apples"` it would be `"apple"`.

```
GET /lemmagen-test/_analyze
{
  "tokenizer": "standard",
  "filter": [
    "lowercase",
    "lemmagen_filter_en"
  ],
  "text": "apples"
}
```

Same as for the `"apple"`

```
GET /lemmagen-test/_analyze
{
  "tokenizer": "standard",
  "filter": [
    "lowercase",
    "lemmagen_filter_en"
  ],
  "text": "apple"
}
```

This could be more visible with the `"I am"` example. The porter_stem emits `["i", "am"]` tokens and lemmagen emits `["i", "be"]`.

```
GET /lemmagen-test/_analyze
{
  "tokenizer": "standard",
  "filter": [
    "lowercase",
    "porter_stem"
  ],
  "text": "I am"
}
```

vs

```
GET /lemmagen-test/_analyze
{
  "tokenizer": "standard",
  "filter": [
    "lowercase",
    "lemmagen_filter_en"
  ],
  "text": "I am"
}
```

So I think the lemmagen is more close to [lemmatisation](https://en.wikipedia.org/wiki/Lemmatisation) then [stemming](https://en.wikipedia.org/wiki/Stemming). I'm unsure about combining both approaches, for example in the query

```
GET /lemmagen-test/_analyze
{
  "tokenizer": "standard",
  "filter": [
    "lowercase",
    "lemmagen_filter_en",
    "porter_stem"
  ],
  "text": "apples"
}
```

the tokens are first lowercased then converted to canonical form and then got rid of the suffixes etc. So the result of the query above would be "appl" (the same one which would be without using the lemmagen).

So I think it depends on your use case and you probably need to try both approaches and measure precision vs recall. I would say that stemmers have usually better recall accuracy, but worse precision (there can be false positive docs) and are usually faster. Lemmatisation on the other hand is usually more precise, but can miss some documents (worse recall).

**Comment by ArtemBernatskyy** [comment]
Thx!
Somewhat I thought that lemmagen doesn't deal with words that it doesn't have in dictionary at all. Now it makes sense.
