### ISSUE TITLE
Elasticsearch 7.17.7

### ISSUE THREAD

**Issue by med502** [vhyza/elasticsearch-analysis-lemmagen#33]
Hello Team,

Would you be able to release plugin compatible with  elasticsearch 7.17.7?

Kind Regards

**Comment by vhyza** [comment]
Hi @med502,

here you go: https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v7.17.7 ;-)

**Comment by med502** [comment]
Thanks!
