### ISSUE TITLE
Elasticsearch 8.6.1

### ISSUE THREAD

**Issue by yuniorsk** [vhyza/elasticsearch-analysis-lemmagen#35]
Hi, would it be possible to support ES version 8.6.1? Thanks a lot

**Comment by vhyza** [comment]
@yuniorsk here you go: https://github.com/vhyza/elasticsearch-analysis-lemmagen/releases/tag/v8.6.1 ;-)

**Comment by yuniorsk** [comment]
Thank you very much 🙏
